name = "kimi-workers-api"
main = "src/index.js"
compatibility_date = "2024-05-28"

[dev]
port = 8787
ip = "localhost"

# 正确配置路由
routes = [
  { pattern = "*/v1/chat/completions*" }
]

# 环境变量配置
[vars]
CORS_ORIGINS = "*"
KIMI_BASE_URL = "https://kimi.moonshot.cn/api"