name = "kimi-cloudflare-worker-js"
main = "src/index.js"
compatibility_date = "2024-05-28"  # 更新兼容日期

kv_namespaces = [
  { binding = "TOKEN_CACHE", id = "REPLACE_WITH_YOUR_KV_NAMESPACE_ID" }
]

[dev]
port = 8787  # 新增开发配置
ip = "localhost"

# 修复 rules 配置
[[routes]]
pattern = "/*"
script = "src/index.js"

# 移除不支持的 tail 配置
# 如果需要日志配置，可以使用 Cloudflare Dashboard 进行设置
type = "redirect"
from = "/*"
to = "/v1/chat/completions"

[tail]
# 日志跟踪配置
format = "json"
sampling_rate = 1.0