name = "kimi-cloudflare-worker-js"
main = "src/index.js"
compatibility_date = "2024-05-28"  # 更新兼容日期

# 移除 KV 命名空间配置，使用内存缓存
# kv_namespaces = [
#   { binding = "TOKEN_CACHE", id = "REPLACE_WITH_YOUR_KV_NAMESPACE_ID" }
# ]

[dev]
port = 8787  # 新增开发配置
ip = "localhost"

# 正确配置路由
routes = [
  { pattern = "*/v1/chat/completions*" }
]

# 环境变量配置
[vars]
CORS_ORIGINS = "*"
KIMI_BASE_URL = "https://kimi.moonshot.cn/api"