name = "kimi-cloudflare-worker-js"
main = "src/index.js"
compatibility_date = "2024-05-28"  # 更新兼容日期

kv_namespaces = [
  { binding = "TOKEN_CACHE", id = "REPLACE_WITH_YOUR_KV_NAMESPACE_ID" }
]

[dev]
port = 8787  # 新增开发配置
ip = "localhost"

[[rules]]
# 路由匹配规则
type = "redirect"
from = "/*"
to = "/v1/chat/completions"

[tail]
# 日志跟踪配置
format = "json"
sampling_rate = 1.0