name = "kimi-cloudflare-worker-js"
main = "src/index.js"
compatibility_date = "2024-03-01"

# 需补充KV命名空间ID
kv_namespaces = [
  { binding = "TOKEN_CACHE", id = "REPLACE_WITH_YOUR_KV_NAMESPACE_ID" }
]

[vars]
KIMI_BASE_URL = "https://kimi.moonshot.cn/api"
CORS_ORIGINS = "*"